version: "3.9"

services:
  mongodb-server:
    container_name: mongodb-server
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    security_opt:
     - no-new-privileges
    cap_drop:
     - ALL
    cap_add:
     - DAC_OVERRIDE
     - SETGID
     - SETUID
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    cap_drop:
     - ALL
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

volumes:
  mongodb:
  mongoconfig: