version: "3.9"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-db
    restart: always
    security_opt:
     - no-new-privileges
    cap_drop:
     - ALL
    cap_add:
     - NET_BIND_SERVICE
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "@docker@2021"
      ACCEPT_EULA: "Y"

