version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis-db
    command: redis-server --appendonly yes
    restart: always
    security_opt:
     - no-new-privileges
    ports:
      - "6379:6379"

